### ISSUE TITLE
Calling nuntius worker results in AppRegistryNotReady exception

### ISSUE THREAD

**Issue by lucargir** [lafranceinsoumise/nuntius#11]
When calling python manage.py nuntius_worker, an AppRegistryNotReady is thrown. I've checked the installation steps and I have set NUNTIUS_SUBSCRIBER_MODEL on the settings file and DJANGO_SETTINGS_MODULE as an env variable...

I am using Django 3.1 with Nuntius 2.2.0.

`INFO 2021-05-14 17:33:46,920 nuntius_worker 77556 4777922048 Started sender process 77559
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/anaconda3/envs/arembe/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/anaconda3/envs/arembe/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/opt/anaconda3/envs/arembe/lib/python3.9/site-packages/nuntius/management/commands/nuntius_worker.py", line 25, in <module>
    from nuntius.models import (
  File "/opt/anaconda3/envs/arembe/lib/python3.9/site-packages/nuntius/models.py", line 4, in <module>
    from django.contrib.contenttypes.models import ContentType
  File "/opt/anaconda3/envs/arembe/lib/python3.9/site-packages/django/contrib/contenttypes/models.py", line 133, in <module>
    class ContentType(models.Model):
  File "/opt/anaconda3/envs/arembe/lib/python3.9/site-packages/django/db/models/base.py", line 108, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/opt/anaconda3/envs/arembe/lib/python3.9/site-packages/django/apps/registry.py", line 252, in get_containing_app_config
    self.check_apps_ready()
  File "/opt/anaconda3/envs/arembe/lib/python3.9/site-packages/django/apps/registry.py", line 135, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
ERROR 2021-05-14 17:33:48,183 nuntius_worker 77556 4777922048 Sender process 77559 unexpectedly quit...
INFO 2021-05-14 17:33:48,194 nuntius_worker 77556 4777922048 Started sender process 77564
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/anaconda3/envs/arembe/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/anaconda3/envs/arembe/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/opt/anaconda3/envs/arembe/lib/python3.9/site-packages/nuntius/management/commands/nuntius_worker.py", line 25, in <module>
    from nuntius.models import (
  File "/opt/anaconda3/envs/arembe/lib/python3.9/site-packages/nuntius/models.py", line 4, in <module>
    from django.contrib.contenttypes.models import ContentType
  File "/opt/anaconda3/envs/arembe/lib/python3.9/site-packages/django/contrib/contenttypes/models.py", line 133, in <module>
    class ContentType(models.Model):
  File "/opt/anaconda3/envs/arembe/lib/python3.9/site-packages/django/db/models/base.py", line 108, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/opt/anaconda3/envs/arembe/lib/python3.9/site-packages/django/apps/registry.py", line 252, in get_containing_app_config
    self.check_apps_ready()
  File "/opt/anaconda3/envs/arembe/lib/python3.9/site-packages/django/apps/registry.py", line 135, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit`

**Comment by jillro** [comment]
Hello ! It's hard to understand where your bug is coming from just from the stacktrace, but two guess :
- have you correctly runned migrations ?
- do you miss `django.contrib.contenttypes` on your `INSTALLED_APPS` ? It should be registered before nuntius.

**Comment by lucargir** [comment]
Hello!
Yes, I did run the migrations and double checked the order in INSTALLED_APPS... :/

**Comment by lucargir** [comment]
Closing issue because this does not replicate with install in new Django project.
