### ISSUE TITLE
Saving anything on Mosaico results in 403 error due to missing CSRF token

### ISSUE THREAD

**Issue by lucargir** [lafranceinsoumise/nuntius#9]
When saving the template or uploading an image from Mosaico's editor, a 403 error is returned due to the lack of a CSRF token in the request:

`
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 54815)
Traceback (most recent call last):
  File "/opt/anaconda3/envs/env/lib/python3.9/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/opt/anaconda3/envs/env/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/anaconda3/envs/env/lib/python3.9/socketserver.py", line 720, in __init__
    self.handle()
  File "/opt/anaconda3/envs/env/lib/python3.9/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/opt/anaconda3/envs/env/lib/python3.9/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/opt/anaconda3/envs/env/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer
----------------------------------------
Forbidden (CSRF token missing or incorrect.): /en/admin/nuntius/campaign/1/mosaico/save/
WARNING 2021-03-16 12:04:05,185 log 82992 123145467338752 Forbidden (CSRF token missing or incorrect.): /en/admin/nuntius/campaign/1/mosaico/save/
[16/Mar/2021 12:04:05] "POST /en/admin/nuntius/campaign/1/mosaico/save/ HTTP/1.1" 403 12885
`

**Comment by jillro** [comment]
Thanks a lot for the fix !!
